DeveloperAcademy-POSTECH/Bingha

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Bingha/Bingha/AppDelegate.swift
- Bingha/Bingha/GoogleService-Info.plist
- Bingha/Bingha/Views/FirebaseController.swift
파이어베이스 초기 설정,
파이어스토어에 데이터 저장
파이어스토어로부터 데이터 로드
#1 
파이어 베이스 관련 패키지 설치로 풀 받고 첫 실행시 빌드 시간이 오래 걸릴 수 있습니다. 모델, 뷰모델 x
> [2022.07.18] feat/settingfirebase>> 파이어베이스 데이터 저장, 로드 로직 작성

- Bingha/Bingha/Model/DecreaseCarbonModel.swift
- Bingha/Bingha/Views/FirebaseController.swift
- 총 이동거리, 총 탄소 배출 저감량 저장 로직 구현 (걷기 완료시 업데이트)
- 모델 변경
#13 
경험치, 레벨 따로 두지않고. 총 탄소 배출 저감량 데이터만 활용해 계산하기로 했습니다. (테리랑 의견 조율 완료)
> [2022.07.19] feat/firebase/iceberg >> 빙하 뷰를 위한 총 이동거리, 총 탄소배출저감량 로직 구현

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha/GoogleService-Info.plist
- Bingha/Bingha/Info.plist
- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- 최초 메인화면 띄울때 오늘 총 탄소 배출 저감량 파이어베이스에서 가지고 오는 로직 완성
- firebasecontroller에서 모델 static으로 변경
#21
> [2022.07.20] feat/connecting/firebase-homeview >> 오늘 총 탄소 배출 저감량 불러오기 로직 적용

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha/Bingha.entitlements
- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/HealthStore.swift
- Bingha/Bingha/Views/Home/Complete/Complete.storyboard
- Bingha/Bingha/Views/Home/Measure/Measure.storyboard
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/ReducedCarbonCalculator.swift
- 측정 화면에서 측정 시작, 종료시 파이어베이스 로직 연결 및 헬스킷 연결. 
#35
> [Feat] #35 측정 화면 버튼 동작 데이터 연결

- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/Iceberg/CircularProgressBarView.swift
- Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
- 총 이동거리에 따른 progressBar 변경 로직
- loadIcebergData메서드 수정
#31
> [2022.07.20] feat/progressBar >> 총 이동거리에 따른 경험치 progressBar 변경 로직 구현

- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
결과 화면에서 측정 화면 데이터 넘겨받는 로직 작성
#38
> [Feat] #38 측정화면, 결과 화면 데이터 연결

- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
> [2022.07.21] feat/HomeViewLottieAnimation >> 측정 화면 로티 애니메이션 백그라운드에서 꺼짐 오류 해결

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha/BinghaRelease.entitlements
- Bingha/Bingha/Views/Iceberg/CircularProgressBarView.swift
- Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
- Bingha/Bingha/Views/IcebergLevelCalculator.swift
- Bingha/Pods/Pods.xcodeproj/project.pbxproj
- 경험치에 따른 progressBar가 채워지는 endPoint를 수정하였습니다
- viewWillAppear를 재정의하여 뷰가 다시 appear될때 data가 refresh되도록 하였습니다
#45
> [2022.07.21] feat/progressFix >> 경험치 바 버그 수정

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha/BinghaDebug.entitlements
- Bingha/Bingha/Extensions/NumericExtension.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
1. 백그라운드 > 포어그라운드 이동 시 타이머 초기화 오류 수정
2. 이동거리 데이터 소수점 개수 1개 설정
#40 
브랜치명 feat으로 잘못 생성했습니다.
> [2022.07.21] feat/TimerDistanceBugFix >> 타이머 초기화 오류 픽스, 이동거리 데이터 소수점 개수설정 완료

- Bingha/Bingha/Views/FirebaseController.swift
- 데이터 없을때 반환 로직 작성
- 0.0으로 반환.
- #49
> [2022.07.23] feat/firebase/fixnondata >> 파이어베이스 데이터 로드 실패시 로직 추가

- Bingha/Bingha/Views/HealthStore.swift
- Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
- Bingha/Bingha/Views/Home/Measure/Measure.storyboard
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
코드 리팩토링 및 수정, 회의를 통한 리팩토링 수정점 반영
#55
> [2022.07.26] feat/coderefactoring >> 코드 리팩토링 및 수정

- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
- 파이어베이스 로직 리팩토링
- 기존 escaping으로 실행 순서 맞췄던 부분 async await로 비동기 로직으로 수정
- 빙하 뷰 viewDidLoad에서 총 탄소 저감량 불러오던 부분 삭제 (최초에 2번 불러오던 이슈 해결)
- 테스트 결과 문제 없음.
- #55 
커리 부분에서 수정된 부분이 많기 때문에 measure 뷰컨쪽 매우매우매우 많이 컨플릭 날 예정
> [2022.07.26] feat/firebase/refactoring >> 파이어베이스 관련 로직 리팩토링 및 수정 

- Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
- Bingha/Bingha/Views/IcebergLevelCalculator.swift
- 메서드명 수정
- 싱글톤 객체 로컬 변수로 받아와 사용
- 뷰 속성 메서드 하나로 묶어서 호출
> [2022.07.26] refactor/bingha >> 코드 리팩토링

- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/Iceberg/Iceberg.storyboard
- 걷기 종료 시 주간 데이터 업데이트 로직 작성
- 만약 그 주에 걷기 데이터가 없을 시 새로 생성
- 이번주부터 3주 전까지 데이터 불러오는 로직 작성
- #58 
- 현재 DB 모델링 상으로는 각각의 주에 대해 요청을 보냄. 즉, 한번에 4번의 요청을 보내고 있는 상황임. 효율성에 대한 부분을 좀 더 고려해 볼 필요 있음.
- #65 머지 완료 되면 테리가 작성해 놓은 뷰 모델 및 모델과 연계지어놓을 예정
> [2022.07.27] feat/firebase/weekdata >> 주간 데이터 업데이트, 로드 로직 구현

- Bingha/Bingha/Views/HealthStore.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
1. HealthStore 싱글톤 클래스의 requestDistanceWalkingRunning함수내에서 실행되던 requestAuthorization함수 분리 
2. 건강 권한요청 도중 타이머가 실행되던 로직 수정
#54
> [2022.07.28] fix/HealthKitLogic >>  HealthKit 권한승인 이후 타이머, 측정시작 동작하도록 로직 수정

- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/Stat/Cells/StatisticsCollectionViewCell.swift
- Bingha/Bingha/Views/Stat/Iceberg/CircularProgressBarView.swift
- Bingha/Bingha/Views/Stat/Iceberg/Iceberg.storyboard
- Bingha/Bingha/Views/Stat/Iceberg/IcebergViewController.swift
- 홈뷰 애니메이션 연결
- 빙하뷰 애니메이션 연결
#72
- 빙하뷰 애니메이션 상단이 흰색이라 프로그레스 바가 보이지 않아 white -> systemgray6로 색상 변경했습니다
- walkingDistance -> walkingDistanceLabel 로 변수명 변경해서 빌드오류나는 부분 해결했습니다
> [2022.07.29] feat/connectAnimation >> 홈뷰, 빙하뷰 애니메이션 연결

- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
1. 거리측정 시작 시 30초마다 거리측정, 탄소절감 표시 안되던 오류 수정
2. ReducedCarbonCalculator 싱글톤 클래스를 변수 인스턴스로 할당해 사용하도록 수정3. 
#76
> [2022.07.29] fix/updateWalkingDistanceLabel >> 측정 시 30초 간격으로 거리측정, 탄소절감 표시되도록 수정

- Bingha/Bingha/Model/StatisticsModel.swift
- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/Stat/Cells/StatisticsCollectionViewCell.swift
- Bingha/Bingha/Views/Stat/Stat.storyboard
- Bingha/Bingha/Views/Stat/StatViewController.swift
- Bingha/Bingha/Views/StatisticsViewModel.swift
- 통계 화면 데이터 연결.
- 오늘, 주, 월 변경시 데이터 변경 로직 작성.
- #82 
- 아직 총 탄소 저감량 부분은 처리 안함. 머지 이후 계속 작업 예정.
> [2022.07.31] feat/statview/connectdata >> 통계 화면 데이터 연결, 세그먼트 컨트롤

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha/Onboarding/Onboarding.storyboard
- Bingha/Bingha/Onboarding/OnboardingCollectionViewCell.swift
- Bingha/Bingha/Onboarding/OnboardingDataModel.swift
- Bingha/Bingha/Onboarding/OnboardingViewController.swift
- Bingha/Bingha/Onboarding/RequestAccessView.storyboard
- Bingha/Bingha/Onboarding/RequestAccessViewController.swift
온보딩 구현 파일 불러왔습니다.
#66 
- storage 파일 및 sceneDelegate 파일 수정 필요합니다
> [Feat] #66 온보딩 구현 파일 재업로드

- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/Stat/Iceberg/IcebergViewController.swift
- 빙하뷰에서 파이어베이스 로드 로직 삭제
- 걷기 종료 시 로컬 데이터 업데이트 로직 추가
- #93
> [2022.07.31] feat/iceberg/fixdataflow >> 빙하뷰에서 파이어베이스 로드 로직 삭제, 걷기 종료 시 로컬 데이터 업데이트 로직 추가

- Bingha/Bingha/Onboarding/OnboardingViewController.swift
- Bingha/Bingha/Onboarding/RequestAccessViewController.swift
- Bingha/Bingha/Views/Launch/LaunchViewController.swift
> [2022.07.31] feat/statview/connect >> 런치스크린, 온보딩 연결

- Bingha/Bingha/Model/DecreaseCarbonModel.swift
- Bingha/Bingha/Model/ReducedCarbonCollectionModel.swift
- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/ReducedCarbonCollectionViewModel.swift
- Bingha/Bingha/Views/Stat/Cells/ReducedCarbonCollectionView.swift
- Bingha/Bingha/Views/Stat/StatViewController.swift
- 일, 주, 월별 데이터 불러와서 저장하는 로직 수정 완료.
- 통계 화면 연결 완료.
- #88
> [2022.07.31] feat/statview/conncet >> 통계 화면 구간 별 탄소 저감량 연결 로직 완성

- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- 총 토탈 탄소 저감량 중복 저장 되던 로직 수정
- 운동 시작시, 측정 뷰에서 오늘 총 탄소 저감량 라벨이 초기화 되던 문제 해결
- #105
> [2022.08.01] feat/debug >> develop 데이터 중복 저장 및 오늘 총 탄소 저감량 초기화 문제 해결

- Bingha/Bingha/Onboarding/RequestAccessView.storyboard
- 접근권한 스토리보드의 내용을 변경했습니다. 
- #109
> [2022.08.01] feat/accessChange >> 접근권한 레이아웃 변경

- Bingha/Bingha/Views/FirebaseController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/Stat/Stat.storyboard
- 통계 화면에서 오늘 운동 모으는 부분 시간으로 텍스트 변경.
- 오늘의 운동을 모아봤어요 -> 당신의 실천을 모아봤어요로 라벨 변경
- 일간 데이터 불러올때 셋으로 불러와서 데이터 순서가 안맞는 문제 발견. 순서 안맞는거 정렬해서 넣는 로직 추가
- #116
> [2022.08.02] feat/chartdesignfix >> 오늘 운동 모으는 부분 시간 텍스트 변경, 라벨 변경,로직 변경

- Bingha/Bingha/Views/ReducedCarbonCalculator.swift
- Bingha/Bingha/Views/Stat/StatViewController.swift
- 한번도 안걸었을때는 기본값 0일 보이게 구현
- 세그먼트 컨트롤 선택 여부에 따라 사용할 뷰모델 생성
#117 
세그먼트랑 연결 로직이 필요합니다
> [2022.08.02] fix/carbonStat >> 통계뷰 로직 수정

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha/AppDelegate.swift
- Bingha/Bingha/Info.plist
1. 세로모드 고정 설정
2. 아이패드 미지원 설정
- #111
> [2022.08.02] build/PortraitIPadSetting

- Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
- Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
> [2022.08.02] feat/binghaCharacter >> 레벨에 맞게 빙하 사이즈 조절

- Bingha/Bingha/Views/CompareViewModel.swift
- Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
- Bingha/Bingha/Views/ReducedCarbonCalculator.swift
- Bingha/Bingha/Views/Stat/StatViewController.swift
- 통계화면 비교 데이터 단위 거리 -> 저감량으로 수정
- 결과 문구 변경.
- #124
> [2022.08.02] feat/statview/fixdata >>  비교 데이터 수정

- Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
- Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
1. 측정 후 레벨업이 됬을 경우 레벨업 안내텍스트 나타나도록 구현
2. 안내텍스트 뷰 애니메이션 구현
- #112
애니메이션은 임의로 fade-in 애니메이션으로 구현했습니다. 차후 변경 가능합니다. 좋은 애니메이션 아이디어가 있으시면 언제든 말씀해주세요.
> [2022.08.02] feat/levelUpNoticeView >> 레벨업 시 완료뷰 안내텍스트 구현

- Bingha/Bingha/Views/Stat/Stat.storyboard
1. 라이센스뷰에 탄소절감 관련 자료출처 기입
- #110
> [2022.08.02] docs/licenseView >> 라이센스뷰 탄소절감 관련 자료출처 기입

- Bingha/Bingha/Views/CompareViewModel.swift
- Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
- 빙하뷰에서 빙하 위치 변경
- 통계뷰 이미지 리매칭
> [2022.08.02] feat/iceberglocation >> 빙하뷰에서 빙하 위치 변경, 통계뷰 이미지 리매칭

- Bingha/Bingha/BinghaDebug.entitlements
- Bingha/Bingha/Views/Home/Complete/Complete.storyboard
1. HealthKit 프레임워크 삭제
2. HealthKit 관련 권한요청 항목 제거
- #134
> [2022.08.03] fix/removeHealthKit >> HealthKit 프레임워크 삭제, 관련 권한요청 삭제

- Bingha/Bingha.xcodeproj/project.pbxproj
- Bingha/Bingha/BinghaRelease.entitlements
- Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
> [2022.08.03] fix/binhaSize >> 빙하 크기 변경

- Bingha/Bingha/Assets.xcassets/ColorSet/ProgressBarBackground.colorset/Contents.json
- Bingha/Bingha/Views/Iceberg/CircularProgressBarView.swift
프로그래스바 백그라운드 색상을 커스텀 컬러로 바꿔줬습니다
#137
> [2022.08.03] fix/progressBar >> 프로그래스바 겹쳐보이는 버그 수정

- Bingha/Bingha/Views/Home/Measure/Measure.storyboard
탭뷰 홈 아이콘을 사람 모양 아이콘으로 변경하였습니다
#139
> [2022.08.03] design/tabview >> 탭뷰 아이콘 변경
